name: Build Fork
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Build project
      run: msbuild -restore -p:Configuration=Release /p:SignAssembly=false
      
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: SABActivator-App
        path: '**\bin\Release\'
